### ISSUE TITLE
How to use this library with strings as utf-8

### ISSUE THREAD

**Issue by PhoneixS** [dadagov125/whirlpool-hash#1]
I want to encode a string which has non-ASCII characters like "España" but it should be hash with UTF-8 encoding (I think that in javascript/typescript strings are encoded in UTF-16). Is it possible to do it with this library?

I see there is a `fromUtf()` but it isn't declared in Typescript and I don't really know if it does what I want.

**Comment by PhoneixS** [comment]
I have managed to do the work with the `toUFT8Array()` function from https://gist.github.com/joni/3760795#file-toutf8array-js to convert it to uft8 and then `String.fromCharCode.apply(String, utf8array)` to make it a string again.

```
let txt = "España";
whirlpool.getHash(String.fromCharCode.apply(String, toUTF8Array(txt)));
console.log(encoders.toHex(hash));
// 98606e01159d4f21ce1b358b5b0db1166c3066776bbc55a9ca4e48da599f29af4f425b75f8b4565e3c181f8a3bc875576eeae434742e016b998f56b77de8c7f6
```

Maybe `getHash` could also accept an array of bytes (in Typescript at least).

**Comment by dadagov125** [comment]
you want me to add a fromUtf for TS?

**Comment by PhoneixS** [comment]
Yes, I think it will be useful (at least for me) and you already have it in the code.

**Comment by dadagov125** [comment]
done in 1.1.5. Can I close the question?

**Comment by PhoneixS** [comment]
Yes, it's ok to close it.
